name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        include:
          - version: v8.0.0000
            neovim: false
            executable: vim
          - version: v9.0.0000
            neovim: false
            executable: vim
          - neovim: true
            executable: nvim
    runs-on: ubuntu-latest
    steps:
      - uses: rhysd/action-setup-vim@v1
        with:
          version: ${{ matrix.version }}
          neovim: ${{ matrix.neovim }}
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run tests
        run: VIM=${{ matrix.executable }} ./test.vim
